### ISSUE TITLE
tokenizerの実装

### ISSUE THREAD

**Issue by urabexon** [Yosshii-42/minishell_test#8]
・make_token_lst.c、add_token_kind.c内で行う。

**Comment by Yosshii-42** [comment]
tokenのkindをより詳しいものに変更した
add_token_kind.c を make_token_kind.cに変更した
token->kind = SYNTAXになった時は、その先の作業を行わずにmake_token_lstに戻る

今後の実装
tokenが特殊文字の時は「対応していない」などのエラー分を表示しminishellに戻る
コマンドがgrepの時は特殊文字処理をしない
